services:
  jpa.test-db:
    image: postgres:latest
    container_name: jpaTest.Db
    environment:
      - POSTGRES_DB=jpaTest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5433:5433