CREATE TABLE IF NOT EXISTS book_rate (

          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
          created_at TIMESTAMP(6) NOT NULL,
          created_by VARCHAR(250) NOT NULL,
          last_modified_at TIMESTAMP(6) NULL,
          last_modified_by VARCHAR(250) NULL,
          is_deleted BOOLEAN NOT NULL DEFAULT false,
          rate INTEGER NOT NULL,
          source VARCHAR(300) NOT NULL,
          book_id BIGINT NOT NULL,
          PRIMARY KEY (id)
);

-- Add FK
ALTER TABLE IF EXISTS book_rate
    ADD CONSTRAINT book_rate_book_id_fk
    FOREIGN KEY(book_id)
    REFERENCES book;

-- Add Indexes
CREATE INDEX IF NOT EXISTS idx_book_rate_book_id
ON book_rate(book_id)