CREATE TABLE IF NOT EXISTS book_series (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      created_at TIMESTAMP(6) NOT NULL,
      created_by VARCHAR(250) NOT NULL,
      last_modified_at TIMESTAMP(6) NULL,
      last_modified_by VARCHAR(250) NULL,
      is_deleted BOOLEAN NOT NULL DEFAULT false,
      numberOfVersions INTEGER NOT NULL,
      PRIMARY KEY(id)
);

-- Adds ManyToMany related Table

CREATE TABLE IF NOT EXISTS book_series_authors (
    book_series_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    PRIMARY KEY(book_series_id, author_id)
);

-- Adds FK
ALTER TABLE IF EXISTS book_series_authors
    ADD CONSTRAINT book_series_id_FK
    FOREIGN KEY (book_series_id)
    REFERENCES book_series;

ALTER TABLE IF EXISTS book_series_authors
    ADD CONSTRAINT author_id_FK
    FOREIGN KEY (author_id)
    REFERENCES author;

