CREATE TABLE IF NOT EXISTS author (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      created_at TIMESTAMP(6) NOT NULL,
      created_by VARCHAR(250) NOT NULL,
      last_modified_at TIMESTAMP(6) NULL,
      last_modified_by VARCHAR(250) NULL,
      is_deleted BOOLEAN NOT NULL DEFAULT false,
      name VARCHAR(250) NOT NULL,
      nationality VARCHAR(250) NOT NULL,
      age INTEGER NOT NULL,
      PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS book (
      id BIGINT generated BY DEFAULT AS IDENTITY,
      created_at TIMESTAMP(6) NOT NULL,
      created_by VARCHAR(250) NOT NULL,
      last_modified_at TIMESTAMP(6) NULL,
      last_modified_by VARCHAR(250) NULL,
      is_deleted BOOLEAN NOT NULL DEFAULT false,
      name VARCHAR(250) NOT NULL,
      isbn VARCHAR(250) NOT NULL,
      author_id BIGINT,
      PRIMARY KEY (id)
);

-- Add Foreign Key
    ALTER TABLE IF EXISTS book
       ADD CONSTRAINT fk_author_author_id
       FOREIGN KEY (author_id)
       REFERENCES author;

-- Add Book Indexes
CREATE INDEX IF NOT EXISTS idx_book_author_id ON book(author_id);

CREATE INDEX IF NOT EXISTS idx_book_isbn ON book(isbn);